services:
  bot:
    image: azalea
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DEBUG_WEBHOOK_URL: ${DEBUG_WEBHOOK_URL}
      DB_PATH: ${DB_PATH:-db.sqlite}
    volumes:
      - type: bind
        source: ./${DB_PATH}
        target: /usr/src/azalea/${DB_PATH}