deleteMessageSecondsOnBan: 0

ephemeralResponses:
  enabled: true
  excludedCategories:
    - "category-id"
  excludedChannels:
    - "channel-id"

userFlags:
  - name: "flag-name"
    roleIds:
      - "role-id"

mediaOnlyChannels:
    - "channel-id"

notices:
  banRequests:
    enabled: true
    channelId: "channel-id"
    threshold: 25
    interval: 3_600_000 # 1 hour
    mentionedRoles:
      - "role-id"
  muteRequests:
    enabled: true
    channelId: "channel-id"
    threshold: 25
    interval: 3_600_000 # 1 hour
    mentionedRoles:
      - "role-id"
commands:
  - name: "Some command"
    value: "some-command"
    embed:
      color: 0xff0000
      title: "Some title"
      description: "Some description"
      fields:
        - name: "Some field"
          value: "Some value"
          inline: true

channels:
  banRequestQueue: "channel-id"
  muteRequestQueue: "channel-id"
  notifications: "channel-id"
  mediaConversion: "channel-id"

roleRequests:
  channelId: "channel-id"
  roles:
    - roleId: "role-id"
      duration: 600000 # 10 minutes

permissions:
  - guildStaff: false
    manageInfractions: false
    viewModerationActivity: false
    manageBanRequests: false
    manageMuteRequests: false
    autoMuteBanRequests: false

    roleIds:
      - "role-id"
    selectMenus:
      - "interaction-name"
    buttons:
      - "interaction-name"
    modals:
      - "interaction-name"
    reactions:
      - "emoji-name"

emojis:
  success: "👌"
  error: "<:emoji-name:emoji-id>"
  quickMute30: "<:emoji-name:emoji-id>"
  quickMute60: "<:emoji-name:emoji-id>"
  purgeMessages: "<:emoji-name:emoji-id>"
  approveRequest: "<:emoji-name:emoji-id>"
  denyRequest: "<:emoji-name:emoji-id>"

logging:
  enabled: true
  excludedCategories:
    - "category-id"
  excludedChannels:
    - "channel-id"

  messages:
    enabled: true
    channelId: "channel-id"
    excludedCategories:
      - "category-id"
    excludedChannels:
      - "channel-id"

  interactions:
    enabled: true
    channelId: "channel-id"
    excludedCategories:
      - "category-id"
    excludedChannels:
      - "channel-id"

  infractions:
    enabled: true
    channelId: "channel-id"
    excludedCategories:
      - "category-id"
    excludedChannels:
      - "channel-id"

  media:
    enabled: true
    channelId: "channel-id"
    excludedCategories:
      - "category-id"
    excludedChannels:
      - "channel-id"

  voice:
    enabled: true
    channelId: "channel-id"
    excludedCategories:
      - "category-id"
    excludedChannels:
      - "channel-id"

  threads:
    enabled: true
    channelId: "channel-id"
    excludedCategories:
      - "category-id"
    excludedChannels:
      - "channel-id"