colors:
    embedDefault: 0x2e3136

forceEphemeralResponse:
    isEnabled: true
    excludedCategories:
        - "360904621524385792" # Internal Channels

roles:
    # Staff roles
    manager:
        roleId: "150074509393788929"
        slashCommands:
            - config

    # Department roles
    infrastructure:
        roleId: "366311313875533824"
        slashCommands:
            - config

logging:
    excludedCategories:
        - "366618544856629248" # Internal Logs

    excludedChannels:
        # Voice channels
        - "328272679188561920" # Management

        # Text channels
        - "temp" #lead-commands
        - "temp" #management-commands
        - "temp" #management
        - "temp" #internal-affairs

    interactionUsage:
        isEnabled: true
        channelId: "" #command-use-logs
