[colors]
embedDefault = "0x2e3136"

[forceEphemeralResponse]
isEnabled = true
excludedCategories = ["012345678912345678"]
excludedChannels = ["012345678912345678"]

[rolePermissions.roleName]
roleId = "012345678912345678"
slashCommands = ["interaction-name"]
messageCommands = ["interaction-name"]
userCommands = ["interaction-name"]
selectMenus = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]

[logging]
excludedCategories = ["012345678912345678"]
excludedChannels = ["012345678912345678"]

[logging.loggingEvent]
isEnabled = true
channelId = "012345678912345678"
excludedCategories = ["012345678912345678"]
excludedChannels = ["012345678912345678"]
