deleteMessageSecondsOnBan = 0
confirmationChannel = "channel-id"
allowedProofChannelIds = ["channel-id"]

[ephemeralResponses]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[[userFlags]]
name = "flag-name"
roleIds = ["role-id"]

[[groups]]
guildStaff = false
manageInfractions = false
viewModerationActivity = false
roleIds = ["role-id"]
selections = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]
reactions = ["emoji-name"]

[[roles]]
id = "role-id"
guildStaff = false
manageInfractions = false
viewModerationActivity = false
manageBanRequests = false
manageMuteRequests = false
autoMuteBanRequests = false
selectMenus = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]
reactions = ["emoji-type"]

[channels]
banRequestQueue = "channel-id"
muteRequestQueue = "channel-id"
mediaConversion = "channel-id"

[banRequestNotices]
enabled = true
channelId = "channel-id"
threshold = 25
interval = 3_600_000 # 1 hour
mentionedRoles = ["role-id"]

[muteRequestNotices]
enabled = true
channelId = "channel-id"
threshold = 25
interval = 3_600_000 # 1 hour

[emojis]
success = "👌"
error = "<:emoji-name:emoji-id>"
quickMute30 = "<:emoji-name:emoji-id>"
quickMute60 = "<:emoji-name:emoji-id>"
purgeMessages = "<:emoji-name:emoji-id>"
approveRequest = "<:emoji-name:emoji-id>"
denyRequest = "<:emoji-name:emoji-id>"

[logging]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[logging.loggingEvent]
enabled = true
channelId = "channel-id"
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]