[ephemeralResponses]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[[groups]]
guildStaff = false
roles = ["role-id"]
selections = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]

[[roles]]
id = "role-id"
guildStaff = false
selectMenus = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]

[logging]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[logging.loggingEvent]
enabled = true
channelId = "channel-id"
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]
