[ephemeralResponses]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[[groups]]
roles = ["role-id"]
selections = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]
staff = true

[[roles]]
id = "role-id"
selections = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]
staff = true

[logging]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[logging.loggingEvent]
enabled = true
channelId = "channel-id"
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]
