[ephemeralResponses]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[permissions.groups.groupName]
roles = ["role-id"]
selections = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]

[permissions.roles.roleId]
selections = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]

[logging]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[logging.loggingEvent]
enabled = true
channelId = "channel-id"
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]
