deleteMessageSecondsOnBan = 0

[ephemeralResponses]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[[groups]]
guildStaff = false
roleIds = ["role-id"]
selections = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]
reactions = ["emoji-name"]

[[roles]]
id = "role-id"
guildStaff = false
selectMenus = ["interaction-name"]
buttons = ["interaction-name"]
modals = ["interaction-name"]
reactions = ["emoji-type"]

[channels]
staffCommands = "channel-id"

[emojis]
success = "👌"
error = "<:emoji-name:emoji-id>"
quickMute30 = "<:emoji-name:emoji-id>"
quickMute60 = "<:emoji-name:emoji-id>"

[logging]
enabled = true
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]

[logging.loggingEvent]
enabled = true
channelId = "channel-id"
excludedCategories = ["category-id"]
excludedChannels = ["channel-id"]